#!/usr/bin/env bash

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config window_placement second_child
yabai -m config window_shadow on

yabai -m config window_border                on
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xffffffff
yabai -m config normal_window_border_color   0xff000000

yabai -m config layout          bsp

yabai -m config external_bar    all:25:0
yabai -m config top_padding     20
yabai -m config bottom_padding  20
yabai -m config left_padding    20
yabai -m config right_padding   20
yabai -m config window_gap      25

yabai -m rule --add app="Digital Colour Meter" manage=off
yabai -m rule --add app="System Preferences" manage=off
yabai -m rule --add app="Activity Monitor" manage=off
yabai -m rule --add app="Font Book" manage=off
yabai -m rule --add app="App Store" manage=off
yabai -m rule --add app="System Information" manage=off
yabai -m rule --add app="Calculator" manage=off
yabai -m rule --add app="Dictionary" manage=off
yabai -m rule --add app="Keka" manage=off
yabai -m rule --add app="Self Control" manage=off

yabai -m rule --add title="floating" manage=off

# https://github.com/koekeishiya/yabai/issues/719#issuecomment-728140216

# focus window after active space changes
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# focus window after active display changes
yabai -m signal --add event=display_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"
