#!/usr/bin/env bash

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config window_placement second_child
yabai -m config window_shadow off

yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xffc9c9c9
yabai -m config normal_window_border_color   0xff7c7c7c

# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier alt

# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

yabai -m config layout          bsp

yabai -m config external_bar    all:25:0
yabai -m config top_padding     25
yabai -m config bottom_padding  25
yabai -m config left_padding    25
yabai -m config right_padding   25
yabai -m config window_gap      30

yabai -m rule --add app="Digital Colour Meter" manage=off
yabai -m rule --add app="System Preferences" manage=off
yabai -m rule --add app="Activity Monitor" manage=off
yabai -m rule --add app="Font Book" manage=off
yabai -m rule --add app="App Store" manage=off
yabai -m rule --add app="System Information" manage=off
yabai -m rule --add app="Calculator" manage=off
yabai -m rule --add app="Dictionary" manage=off
yabai -m rule --add app="Keka" manage=off
yabai -m rule --add app="Self Control" manage=off
yabai -m rule --add app="KeePassXC" manage=off
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="RetroArch" manage=off
yabai -m rule --add app="Aviary" manage=off
yabai -m rule --add app="Streaks" manage=off
yabai -m rule --add app="Poolside FM" manage=off

yabai -m rule --add title="floating" manage=off

yabai -m rule --add app="Skim" manage=on

# https://github.com/koekeishiya/yabai/issues/719#issuecomment-728140216
